create table if not exists public.users (
  id bigint generated by default as identity primary key,
  auth_user_id uuid unique not null references auth.users(id) on delete cascade,
  email text not null,
  name text not null,
  is_admin boolean not null default false,
  is_payment_confirmed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.matches (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  team1_name text not null,
  team2_name text not null,
  team1_logo_url text,
  team2_logo_url text,
  team1_score integer not null default 0,
  team2_score integer not null default 0,
  timer_duration integer not null default 2700,
  "current_time" integer not null default 0,
  is_timer_running boolean not null default false,
  current_half integer not null default 1,
  design_theme text not null default 'classic',
  is_active boolean not null default true,
  is_visible boolean not null default true,
  half_time_offset integer not null default 0,
  show_notification boolean not null default false,
  current_notification_text text,
  show_lineups boolean not null default false,
  timer_start_timestamp double precision,
  timer_server_time double precision,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.match_players (
  id bigint generated by default as identity primary key,
  match_id bigint not null references public.matches(id) on delete cascade,
  team integer not null,
  player_name text not null,
  player_number integer,
  is_starter boolean not null default true,
  is_on_field boolean not null default true,
  position text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.match_events (
  id bigint generated by default as identity primary key,
  match_id bigint not null references public.matches(id) on delete cascade,
  event_type text not null,
  player_name text not null,
  team integer not null,
  minute integer not null,
  description text,
  substituted_player_name text,
  is_visible boolean not null default true,
  is_broadcast boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  amount numeric(10,2) not null,
  status text not null default 'pending',
  payment_method text,
  transaction_id text,
  confirmed_by_admin_id bigint references public.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.site_statistics (
  id bigint generated by default as identity primary key,
  event_type text not null,
  page_path text,
  user_agent text,
  ip_address text,
  auth_user_id uuid references auth.users(id),
  session_id text,
  additional_data jsonb,
  created_at timestamptz not null default now()
);

alter table public.users enable row level security;
alter table public.matches enable row level security;
alter table public.match_players enable row level security;
alter table public.match_events enable row level security;
alter table public.payments enable row level security;
alter table public.site_statistics enable row level security;

create policy "public can read visible matches" on public.matches for select using (is_visible = true);
create policy "owners can manage matches" on public.matches for all using (
  user_id in (select id from public.users where auth_user_id = auth.uid())
);
create policy "public can read match players" on public.match_players for select using (true);
create policy "public can read match events" on public.match_events for select using (is_visible = true);
create policy "owners can manage match players" on public.match_players for all using (
  match_id in (select id from public.matches where user_id in (select id from public.users where auth_user_id = auth.uid()))
);
create policy "owners can manage match events" on public.match_events for all using (
  match_id in (select id from public.matches where user_id in (select id from public.users where auth_user_id = auth.uid()))
);
create policy "users can read own profile" on public.users for select using (auth_user_id = auth.uid());
create policy "users can update own profile" on public.users for update using (auth_user_id = auth.uid());
create policy "users can create own payments" on public.payments for insert with check (
  user_id in (select id from public.users where auth_user_id = auth.uid())
);
create policy "users can read own payments" on public.payments for select using (
  user_id in (select id from public.users where auth_user_id = auth.uid())
);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.users (auth_user_id, email, name)
  values (new.id, coalesce(new.email, ''), coalesce(new.raw_user_meta_data->>'full_name', new.email, 'Користувач'))
  on conflict (auth_user_id) do update set email = excluded.email, updated_at = now();
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute procedure public.handle_new_user();
